include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # 1. OPT OUT: Don't force me to write docs for everything
    public_member_api_docs: false
    
    # 2. OPT IN: Force vertical widgets (Great for AI & DeX)
    require_trailing_commas: true
    
    # 3. OPT IN: Extra safety for your Repository logic
    avoid_print: true